# Generated by Django 5.1.2 on 2024-11-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Bankloan',
        ),
    ]
