# Generated by Django 5.1.2 on 2024-11-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0002_rename_employee_bankloan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankloan',
            old_name='eid',
            new_name='loanid',
        ),
    ]
